src/Predict/Predict.js

Once the User selects the model name, the app will pre-select the first model version in the list as well as a postprocessing function (if that postprocessing function is in the name of the model).

pre-populate the model version and post-process function after model selection

---

src/FileUpload/FileUpload.js
src/Predict/Predict.js

There are some elements that Selenium (running in the `kiosk-benchmarking` pod) needs to be able to identify reliably. Assigning ids to these components is the simplest way to accomplish that.

Adding component ids

---

server/controllers/predict.controller.js
server/controllers/train.controller.js

When a new key is added to redis, also add a key to the work queue.
Parse new `created_at` and `updated_at` timestamps, and process as strings. Save them as ISOFormat strings.

Redis queue for processing

---

package.json
server/config/redis.js
server/controllers/model.controller.js
server/controllers/predict.controller.js
server/controllers/redis.controller.js
server/controllers/train.controller.js
server/routes/index.js
src/Predict/Predict.js
yarn.lock

Created a new batch API that handles lists of objects rather than a single object for both the `/predict` and `/redis/status` endpoints.
Additionally, created async Redis client calls for calling many requests simultaneously.
Finally, updated formatting of redis keys (using ":"s as separators rather than "_") and using the `uuid` package for random string rather than `Date.now()` for guaranteed uniqueness.

Batch API for creating and monitoring multiple jobs simultaneously

---

package.json
server/config/redis.js
yarn.lock

`redis-ha` package prevents the redis client from only connecting with redis READONLY slaves.

update the redis client to use redis-ha to prevent READONLY errors.

---

.babelrc
Dockerfile
package.json
server/config/express.js
src/App/App.js
src/Container/Container.js
webpack.prod.js
yarn.lock

This PR prevents the warning that the bundle.js file is too large by using the `CompressionPlugin` and `UglifyJsPlugin`.  Additionally, it uses `@loadable/component` to lazy load components, aiding in the chunking of the bundle.js payload.  Finally, the Dockerfile and package.json were changed to call `yarn build` inside the Dockerfile, and remove it from the entrypoint.  The source files are then removed from the Dockerfile to lighten the image.

Use webpack best practices to reduce the size of bundle.js

---

package.json
server/config/config.js
server/config/redis.js
yarn.lock

`REDIS_SENTINEL` is parsed from the environment to pass the `config.redis` credentials to `ioredis` as a sentinel or as a regular client.  This enables backwards compatibility with previous versions using `node-redis`, but `REDIS_SENTINEL` will be required in the environment in order to use sentinel mode.

Use REDIS_SENTINEL to determine which type of redis client to create.

---

README.md
server/config/config.js
server/controllers/predict.controller.js
server/routes/index.js
src/Predict/Predict.js
webpack.prod.js

This PR enables the React frontend to be isolated from the defined job types, and enables extensions to the list of job types easily with the environment variable `QUEUES`.  This should be a comma-separated string, such as "segmentation,tracking".  This is then split into a list inside the config object, and exposed via the backend route `/jobtypes`.  The frontend queries this API to populate the drop-down, and capitalizes it for display purposes.

All job types are defined in the environment and exposed with a backend route.

---

server/controllers/predict.controller.js

Enable jobs to shortcut the label detection by including the label in the creation POST request.
For example:
```bash
{
....,
"dataLabel": 0,
....,
}
```
Additionally, this PR adds a default value for "dataScale" if it is not passed in the request.

Add "dataLabel" as optional parameter for predict API

---

.travis.yml

Rarely, the `curl` command to install `yarn` during the TravisCI tests has failed, causing a failed build. `travis_retry` will automatically retry the failed command (up to 3 times). This should prevent any randomly failed installations.

travis_retry yarn installation during CI/CD testing

---

.eslintrc.yml
package.json
yarn.lock

The `loadable(import())` pattern was throwing errors as ESLint could not understand how to read it. This is resolved by using the `babel-eslint` parser to help parse stage 3 proposals.
The `jsx-uses-vars` setting is also removed from the `.eslintrc.yml` file as it is no longer valid.

Fix ESLint bug.

---

package.json
server/config/swagger.js
server/routes/index.js
src/App/App.js
yarn.lock

Swagger Docs are a great way to document APIs. This PR uses `swagger-jsdocs` to generate a Swagger JSON spec from decorated jsdocs on the API routes.  This JSON spec is served over /api/swagger.json.  The frontend react app uses the `sagger-ui-react`'s `SwaggerUI` component to consume that JSON endpoint and generate the documentation page.
Fixes #97

Auto swagger-docs with swagger-ui-react and swagger-jsdocs.

---

src/FileUpload/FileUpload.js

Only single file uploads are supported by the backend, so don't allow the user to think they are uploading a folder.
Fixes #119

If more than one file is uploaded, throw an error.

---

package.json
src/Predict/Predict.js
yarn.lock

Update the error handling to check for "reason" in addition to the "failures" field. "failures" is only populated by zip consumers, and is a URL encoded dictionary of Redis hashes to failure reasons. The `query-string` npm package was added for parsing the URL encoded "failures" string into an object, and each object is then logged as errors on the page for the user. The download button is still available for successful files. (Fixes vanvalenlab/kiosk-console#379)
Additionally, some CSS styling was added to fix the error formatting (`style={{whiteSpace: 'pre-line'}}`). This better displays the new line characters to keep the visual structure of the stack trace. (Fixes #118)
---

Display errors for failed zip jobs and improve error formatting.

---

server/controllers/upload.controller.test.js

The GCP test for the /upload route using `multer` was not using the proper `await` command and would occasionally fail. This PR adds `await` and should fix the test.

Fix /upload test for GCP.

---

server/config/redis.js

There are too many open Redis connections because the Redis client is created in each request - and they are never closed! This PR disconnects the redis connection after each call, regardless of success or failure. This should limit the number of open connections.

Disconnect the redis connection after each request.

---

src/About/About.js
src/Faq/Faq.js

Caliban is now DeepCell Label, and this should be reflected in the FAQ and About pages.

Refactor Caliban to DeepCell Label.

---

README.md
server/config/config.js
server/config/multer.js
server/controllers/model.controller.js
server/controllers/upload.controller.js

Deprecate `CLOUD_PROVIDER`, `GCLOUD_STORAGE_BUCKET` and `AWS_S3_BUCKET` in favor of a single `STORAGE_BUCKET` that includes the bucket protocol (e.g. `s3://`). This simplifies the required environment variables.

Infer cloud provider from STORAGE_BUCKET protocol.

---

package.json
yarn.lock

Fixes the following CVEs:
* CVE-2020-28477
* GHSA-r92x-f52r-x54g

Update @google-cloud/storage to ^5.8.1 and react-scripts to ^4.0.3

---

server/controllers/predict.controller.js
src/App/App.js
src/Predict/ChannelForm.js
src/Predict/ChannelForm.test.js
src/Predict/ModelDropdown.js
src/Predict/Predict.js
src/Predict/jobData.js

- Create a `ChannelForm` component that allows for RGB/BW selection
- Send the selected values to the backend API as `"channels"` as a comma-separated string of integers.
Fixes #146

Allow users to define which channels to use for a given model.

---

src/Predict/ChannelForm.js
src/Predict/JobCard.js
src/Predict/Predict.js
src/Predict/ResolutionDropdown.js
src/Predict/ResolutionDropdown.test.js
src/Predict/jobData.js

As discussed in #165, the `ScaleForm` is a bit too unintuitive for users. It's not clear what the correct "scale" should be. This PR replaces the `ScaleForm` with a manual dropdown with common microns-per-pixel values (and the zoom level used with them). This way, the user can select if their data is 40x or 10x instead of trying to guess at the correct scale.
I think there is still room for a manual input form for image mpp, but for now, I think that the ballpark resize values will be helpful and intuitive.
Fixes #165

Replace `ScaleForm` with new `ResolutionDropdown`.

---

src/Predict/Predict.js
src/Predict/jobData.js

This adds data to each each job type on whether opening results in DeepCell Label is supported. It adds some internal state to track what job type was last submitted (so switching the selected type to mesmer after getting polaris results won't show the button), and adds a `canOpenInLabel` field to each jobData.
I'm working on adding tests for this addition by testing that a completed mesmer job shows the button while a completed polaris job does not, but it's taking some time to figure out how to mock the API responses to make the Predict component reach it's completed state. It seems like first `/api/jobtypes` is called, then `/api/predict`, then `/api/redis`. @MekWarrior do you know where I can look up the expected responses for the API? We can also wait on adding tests if it's too much …

Parametrize whether to open job results in Label

---

server/controllers/predict.controller.js
src/Predict/ChannelForm.js
src/Predict/ChannelForm.test.js
src/Predict/MesmerForm.js
src/Predict/ModelDropdown.js
src/Predict/PolarisForm.js
src/Predict/Predict.js

This PR introduces two new components MesmerForm and PolarisForm that contain workflow specific forms so that those jobs can be parameterized. The behavior for mesmer is unchanged, which polaris can now pick what segmentation model to use and which channels to use segmentation.
Each Form component updates the jobForm object in the Predict component. We now send the jobForm object to the /predict route, which unpacks the form to send to the consumer. As we expand the supported workflows and the contents of the jobForm varies more, we'll need to revisit how the route handles the jobForm contents.
I've also refactored the ChannelForm to simplify the state for selected channels. Previously, there were four collaborating variables that tracked the selected channels including:
- targetChannels …

Add more options for Polaris jobs

---

src/Predict/JobForm/DimensionOrderDropdown.js
src/Predict/JobForm/SegmentationForm.js

This refactor the DimensionOrderDropdown component into its own file and adds a tooltip to clarify what it does. I also made the styling consistent with the channel form. Here's what it looks like

Separate DimensionOrderDropdown and add tooltip

---

src/Predict/JobForm/PolarisForm.js
src/Predict/JobForm/SegmentationForm.js
src/Predict/jobData.js

This PR changes the default settings for the segmentation and Polaris job cards to match the settings needed to analyze the provided example files.

Change default job card settings to match example files

---

src/Predict/JobCompleteButtons/VisualizeButton.js
src/Predict/jobData.js

This connects the kiosk frontend to the caliban visualizer on tracks.deepcell.org. Now that the field is set for caliban, the View Results button will appear after caliban jobs finish and will submit the result to the visualizer.

Add visualizer to jobData for caliban

---

src/Predict/JobForm/PolarisForm.js
src/Predict/jobData.js

This PR updates the file name for the Polaris example prediction to temporarily address [this issue](https://github.com/vanvalenlab/kiosk-console/issues/458). It also changes the preset suggested channel order for the Polaris job card.

Update name of Polaris example file

---

src/Predict/JobCompleteButtons/VisualizeButton.js
src/Predict/Predict.js
src/Predict/jobData.js

This switches all the visualizers to use DeepCell Label with editing enabled.
It also adds visualizer support for the segmentation model. As the segmentation consumer supports different dimension orders, we need to pass this dimension order to DCL to load the images properly. The mesmer redis consumer already sends a dimension order that is forwarded to DCL. I've wired an effect to update the dimension order when the jobForm changes, but this is a bit hacked together and should be revisited as we support flexible dimension orders for more models.
Merging this will let us take viewer.deepcell.org, spots.deepcell.org, and tracks.deepcell.org offline and close https://github.com/vanvalenlab/deepcell-label/pull/243.

Switch all visualizers to label.deepcell.org
